[project]
name = "indexer-relay"
authors = ["IndexerTeam"]
description = "Decentralized indexing and data relay protocol"
telemetry = false
requirements = []
[contracts.relay-access]
path = "contracts/relay-access.clar"
depends_on = []

[contracts.relay-core]
path = "contracts/relay-core.clar"
depends_on = []

[contracts.relay-integrity]
path = "contracts/relay-integrity.clar"
depends_on = []

[contracts.relay-metadata]
path = "contracts/relay-metadata.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
